In [2]:
import pandas as pd

In [4]:
anno = pd.read_csv("annotations_by_frame.csv")
anno = anno.fillna(0)

anno.head()

,Unnamed: 0,file_name,timestamp,car,truck,bicycle,motorbike,bus,total
0,0,data/task_street_traffic-helsinki-269-8191-202...,0.5,0.0,0.0,0.0,0.0,0.0,0.0
1,1,data/task_street_traffic-helsinki-269-8191-202...,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,data/task_street_traffic-helsinki-269-8191-202...,1.5,0.0,0.0,0.0,0.0,0.0,0.0
3,3,data/task_street_traffic-helsinki-269-8191-202...,2.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,data/task_street_traffic-helsinki-269-8191-202...,2.5,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
anno.shape

(8303, 9)

In [6]:
def get_video_name(name):
    name = name.split("data/task_")[1]
    name = name.split("-2021")[0]
    name = name.split(".mp4")[0]
    return name + ".mp4"

In [7]:
anno["video_name"] = anno["file_name"].apply(get_video_name)

In [10]:
anno[:20]

,Unnamed: 0,file_name,timestamp,car,truck,bicycle,motorbike,bus,total,video_name
0,0,data/task_street_traffic-helsinki-269-8191-202...,0.5,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
1,1,data/task_street_traffic-helsinki-269-8191-202...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
2,2,data/task_street_traffic-helsinki-269-8191-202...,1.5,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
3,3,data/task_street_traffic-helsinki-269-8191-202...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
4,4,data/task_street_traffic-helsinki-269-8191-202...,2.5,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
5,5,data/task_street_traffic-helsinki-269-8191-202...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
6,6,data/task_street_traffic-helsinki-269-8191-202...,3.5,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
7,7,data/task_street_traffic-helsinki-269-8191-202...,4.0,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
8,8,data/task_street_traffic-helsinki-269-8191-202...,4.5,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
9,9,data/task_street_traffic-helsinki-269-8191-202...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
10,10,data/task_street_traffic-helsinki-269-8191-202...,5.5,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
11,11,data/task_street_traffic-helsinki-269-8191-202...,6.0,0.0,0.0,0.0,0.0,0.0,0.0,street_traffic-helsinki-269-8191.mp4
12,12,data/task_street_traffic-helsinki-269-8191-202...,6.5,1.0,0.0,0.0,0.0,0.0,1.0,street_traffic-helsinki-269-8191.mp4
13,13,data/task_street_traffic-helsinki-269-8191-202...,7.0,1.0,0.0,0.0,0.0,0.0,1.0,street_traffic-helsinki-269-8191.mp4
14,14,data/task_street_traffic-helsinki-269-8191-202...,7.5,1.0,0.0,0.0,0.0,0.0,1.0,street_traffic-helsinki-269-8191.mp4
15,15,data/task_street_traffic-helsinki-269-8191-202...,8.0,1.0,0.0,0.0,0.0,0.0,1.0,street_traffic-helsinki-269-8191.mp4
16,16,data/task_street_traffic-helsinki-269-8191-202...,8.5,1.0,0.0,0.0,0.0,0.0,1.0,street_traffic-helsinki-269-8191.mp4
17,17,data/task_street_traffic-helsinki-269-8191-202...,9.0,2.0,0.0,0.0,0.0,0.0,2.0,street_traffic-helsinki-269-8191.mp4
18,18,data/task_street_traffic-helsinki-269-8191-202...,9.5,2.0,0.0,0.0,0.0,0.0,2.0,street_traffic-helsinki-269-8191.mp4
19,0,data/task_20201223t000009_52333-2021_06_05_22_...,0.5,0.0,0.0,0.0,0.0,0.0,0.0,20201223t000009_52333.mp4

In [17]:
bosch=anno[~anno['video_name'].str.contains('street')]

In [19]:
bosch.head()

,Unnamed: 0,file_name,timestamp,car,truck,bicycle,motorbike,bus,total,video_name
19,0,data/task_20201223t000009_52333-2021_06_05_22_...,0.5,0.0,0.0,0.0,0.0,0.0,0.0,20201223t000009_52333.mp4
20,1,data/task_20201223t000009_52333-2021_06_05_22_...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,20201223t000009_52333.mp4
21,2,data/task_20201223t000009_52333-2021_06_05_22_...,1.5,0.0,0.0,0.0,0.0,0.0,0.0,20201223t000009_52333.mp4
22,3,data/task_20201223t000009_52333-2021_06_05_22_...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,20201223t000009_52333.mp4
23,4,data/task_20201223t000009_52333-2021_06_05_22_...,2.5,0.0,0.0,0.0,0.0,0.0,0.0,20201223t000009_52333.mp4

In [20]:
bosch.shape

(1444, 10)

In [29]:
blabel=bosch.iloc[:,2:].reset_index(drop=True)

In [35]:
blabel.to_csv('../bosch_labels.csv')